db = new Mongo().getDB("goat_db");

db.createCollection('goat_facts', { capped: false });

db.goat_facts.insert([
    {"fact": "Goat uptime is measured in mean-time-between-naps, not in 9s."},
    {"fact": "No KPIs, QBRs, or TPS reports."},
    {"fact": "Anyone who says, 'sounds like someone's got a case of the Mondays!' is liable to get their ass kicked."},
    {"fact": "Every day is a work-from-home day."},
    {"fact": "Goats don't smell any worse than your officemate who forgot to shower. Again."},
    {"fact": "Goats don't mind if you forgot to shower (again)."},
    {"fact": "You never need to run an ad blocker on your goat."},
    {"fact": "There are no goat user interface elements that are 'lickable' in any way, shape, or form. Unlesss you're another goat, of course."},
    {"fact": "Goatsoft won't sneak into your farm and replace your goats with the latest GoatOS version 10."},
    {"fact": "Rebooting a goat means you just kick it harder."},
    {"fact": "You never waste time watching your goat compile."},
    {"fact": "Goats are much easier to shave than yaks are."},
    {"fact": "Goats have never heard of Patch Tuesday."},
    {"fact": "Nobody will ever ask you if you've rebooted your goat."},
    {"fact": "Goats are basically the OG of continous delivery."},
    {"fact": "There are no goats in the cloud."},
    {"fact": "The support escalation policy for your goats is sending the kids out to do their chores."},
    {"fact": "Nobody's ever heard of a Goat-to-Butt plugin for Chrome. Yet."},
    {"fact": "There's no goat plugin for Splunk; and if you tried to ...plug in..., the goat would probably kick your ass anyway."},
    {"fact": "If you transpose a few characters in a goat's name, it will still answer as much as it ever would."},
    {"fact": "You don't have to monitor the utilization on a goat."},
    {"fact": "Milk a goat and the goat stays milked for a while."},
    {"fact": "There are no 32-bit goats."},
    {"fact": "You don't have to do a demo on a goat. And if you ever do, the goat will do what it's supposed to do and there's not a lot that can keep it from doing it."},
    {"fact": "When a goat 'goes down', you just bury it and buy a new goat."},
    {"fact": "Left alone, Billy goats and Nanny goats do what they're supposed to do. You don't need to format them, monitor them, be on-call for them, step, trace or inspect registers."},
    {"fact": "Nobody cares if you're not a Certified Goat Engineer yet."},
    {"fact": "When you go back to visit the family, nobody ever asks you to fix their goat while the roast is cooking."},
    {"fact": "Nobody can lie in a job interview about their goat experience."},
    {"fact": "Goats don't page you in the middle of the night."},
    {"fact": "When it comes to 'software' (food), EVERYTHING is compatible with a goat."},
    {"fact": "You don't need to buy a 'goat 2017' to fix all the bugs in your goat 2012."},
    {"fact": "You can tell whether a goat has been 'debugged' by looking at it."},
    {"fact": "Goats don't become obsolete. If they do, as long as you didn't neuter them, they make the necessary upgrades themselves."},
    {"fact": "The commute time is very short, since the barn is just outside."},
    {"fact": "No dress code. Of any kind. EVER."},
    {"fact": "You always have the right 'file permissions' to milk a goat."},
    {"fact": "If a goat gives too many timeout errors, or if performance is generally unacceptable; it just means you're having goat steak for dinner."},
    {"fact": "When milking your goats, you either have a bucket or you don't. Nobody tries to sell you on an annual license."},
    {"fact": "The bucket either leaks or it doesn't, and it never gets corrupt carrying it out to the barn."},
    {"fact": "You don't need to 'free up some memory' before you milk a goat."},
    {"fact": "You don't need to call a staff meeting to make sure everyone's milking goats the same way."},
    {"fact": "Just about any barnyard animal is fault tolerant (except some cows)."},
    {"fact": "You don't need to sign in with the front desk if you need to milk a goat on a weekend."},
    {"fact": "You don't need to worry if you've been spending a lot of time milking what you will later find out to have been an improperly labelled 'development goat'."},
    {"fact": "There is no such thing as a 'preferred goat,' and your 'goat context' is always correct"},
    {"fact": "You'll never have your goat access disabled because of intrusion detection."},
    {"fact": "There's no such thing as goat fan-bois."},
    {"fact": "Carpal tunnel is guaranteed. Don't worry about it."},
    {"fact": "A goat has all the 'patches' it will ever need. If it doesn't it, just means you're having goat steak for dinner."},
    {"fact": "Goats that become full do an automatic 'core dump' but they take care of getting themselves reset and on-line. You just have to clean up."},
    {"fact": "You do not need to worry about defragmenting or compressing your goat."},
    {"fact": "Goats never have to be zipped, archived or converted to Goat-32."},
    {"fact": "As long as the stable hasn't caught fire, a goat couldn't care less about a power surge."},
    {"fact": "Goats don't have to be backed up at night."},
    {"fact": "Each and every one of the parts of a goat use the same interrupt, and the goat works just fine anyway."},
    {"fact": "A goat is a goat is a goat."},
    {"fact": "You don't EVER restart a goat. You do shut them down sometimes and it's the first step in many of your recipes."},
    {"fact": "Nobody ever needed to draft up a goat-milking requirements document."},
    {"fact": "You deliver applications to goats. Goats do not deliver applications to you."},
    {"fact": "A goat will do practically anything do get more comfortable. Computers have been known to display the same error message over and over again, all day, without regard to how frequently or how hard the monitor has been hit, slapped, punched or kicked."},
    {"fact": "You don't have to log off of a goat and listen to some silly 'Exit Goat' sound effect for the next several minutes."},
    {"fact": "You won't find out from your next phone bill that you milked your goat too much for your budget."},
    {"fact": "On a goat, the SYS$ERR.LOG file is ALWAYS EMPTY."},
    {"fact": "Operating systems come & go, but goats will probably never be 'orphaned' as they are expected to be produced by their manufacturer for quite some time to come."},
    {"fact": "There are no workstation licensing issues with goats."},
    {"fact": "You don't get in trouble for milking a goat during business hours, and nobody cares if you reformat it."},
    {"fact": "If it's late and you have a lot of goat-milking to do, at least you can see your kids before they have to go to bed. You can probably even make them help you milk your goats."},
    {"fact": "You don't need 16 gigs of RAM to get started milking your goat."},
    {"fact": "Goat security is applied completely, thoroughly, and with all the features you'll ever need, using a stake and a rope."},
    {"fact": "Nobody ever got a general protection fault milking a goat."},
    {"fact": "You don't need to worry about your whole goat herd locking up if you put an ethernet goat and a token-ring goat together in the same stable."},
    {"fact": "You don't name goats, but if you do then non-unique names won't interfere with your ability to access any of the goats."},
    {"fact": "You will never be asked to check a box that says, <i>Make this my default goat-milking bucket</i>."},
    {"fact": "You do not want, need, or desire in any way for goats to run at a higher clock speed. And they don't."},
    {"fact": "You do not need to use a wrist strap to ground yourself before milking, and there's never a need to put your goat in a little plastic baggie. Unless making goat steak."},
    {"fact": "There really aren't too many ways to improperly shut down a goat."},
    {"fact": "When surrounded by a room full of younger goat farmers, you don't need to worry about dating yourself talking about 300-baud or 4.7-Mhz goats."},
    {"fact": "You do not need to buy anything to 'uninstall' a goat. Maybe a gun or a knife."},
    {"fact": "Once you've filled a bucket with goat milk, the goat can crash and it doesn't matter whether you've 'saved' or not. Just don't spill."},
    {"fact": "When you buy a new goat, the goat does not need to re-write registry keys on the farm that could have unforeseen effects on the other animals already residing there."},
    {"fact": "There are no easter eggs in a goat."},
    {"fact": "Goats instinctively know how to 'install RAM' by themselves."},
    {"fact": "You never need to learn Goat 2012, Goat Perfect 8, or Goat 123"},
    {"fact": "Goats don't need a per-bucket license."},
    {"fact": "You will never spend 4 hours upgrading a goat over the wire."},
    {"fact": "There is no Goat Ops."},
    {"fact": "Goats follow upgrade procedures."},
    {"fact": "Goats eat org charts."},
    {"fact": "If a goat gets an uncleanable virus, you shoot it."},
    {"fact": "If a goat has a non-terminal virus it just does the poo-poo."},
    {"fact": "Goats don't need pagers and never get a 'please advise'."},
    {"fact": "Goats don't have to worry about whether or not it's HIPAA compliant."},
    {"fact": "A goat farmer doesn't care if people can't remotely access their herd."},
    {"fact": "There's no such thing as Goats-as-a-service. Except for the local butcher."},
    {"fact": "No one gives a rat's ass if the goats aren't talking to each other."},
    {"fact": "Ever heard of a proprietary goat?"},
    {"fact": "No goat analysis meetings."},
    {"fact": "No goat control meetings."},
    {"fact": "No meetings."},
    {"fact": "Goats will never need service pack 4."},
    {"fact": "A goat might bite you in the ass, but he won't fuck you."},
    {"fact": "Goats don't ever ask stupid questions."},
    {"fact": "Goats don't need two-factor auth policies."},
    {"fact": "Your YubiKey isn't ever going to work on a goat. It would kick your ass if you tried."},
    {"fact": "If a goat takes a 'dump' in the middle of the night, you take care of it when you damn well feel like it."},
    {"fact": "Nobody will fire you for connecting 'diskless goats' into a 'goat server' instead of a mainframe goat and a bunch of cheap 'dumb goats'."},
    {"fact": "Counting from zero instead of one doesn't apply to anything goat farmers do and looks stupid. Hexadecimal is unheard of."},
    {"fact": "When you sell a goat, you don't need to export it to a format that will be understood by the buyer's ancient goat-reading software."},
    {"fact": "All your stuff will still work when you buy your 100th goat, and your 256th goat, and your 65,536th goat..."},
    {"fact": "People don't walk up to goat farmers at parties and whine about how they just got a French Alpine and don't know how to milk it."},
    {"fact": "Nobody can go through your goat and get you in trouble for what they find in there."},
    {"fact": "You don't have to administer a 'user acceptance test' when you deliver goat cheese."},
    {"fact": "You don't need any special utilities to delete a goat that is not empty."},
    {"fact": "You don't need or want goats on your desktop, or shortcuts to goats on your desktop. Most goat farmers don't have desktops."},
    {"fact": "Nothing a goat farmer does requires a mouse. If you have mice you get a cat."},
    {"fact": "Goat farmer error messages: Goat not found; Goat dead; Goat not awake; Too soon after last milking; Billy goat detected. That's about all. You don't need silly numbers for these, and you don't need to look them up anywhere or check them out at <a href='http://goat.com'>goat.com</a>."},
    {"fact": "There are no read-only goats. There are no hidden or system goats."},
    {"fact": "You don't need to mail anyone a core dump from a goat to fix a problem. The only time you would do this is to CAUSE a problem."},
    {"fact": "A goat that doesn't know what time it is will work just fine."},
    {"fact": "A goat that is not Y2K compliant will simply eat and shit. Because that's what goats do."},
    {"fact": "You don't need to authorize the purchase of a new goat, you simply encourage your goats to make one from existing parts."},
    {"fact": "A goat doesn't have enough fingers to press &lt;Shift&gt;&lt;Ctrl&gt;&lt;Alt&gt;&lt;Esc&gt;"},
    {"fact": "Goats don't argue about it being another goat's problem. They just kick each others ass."},
    {"fact": "If a goat had to document every time it took a shit, we would be out of forests."},
    {"fact": "Goats don't give a shit about email."},
    {"fact": "The only way a goat can deliver an 'application' is through its ass."},
    {"fact": "Goats can't get their benefits revoked; they're just made into goat steak for dinner."},
    {"fact": "A goat farmer doesn't have to provide documentation on their goat's ability to produce milk after the year 2000."},
    {"fact": "GoatEng."},
    {"fact": "Goats don't have to wait half an hour to cool down before you can change the projection bulb."},
    {"fact": "Goats aren't designed with consumables that require a trip back to the workshop to replace."},
    {"fact": "You don't have to buy hi-res KVMs for your goats."},
    {"fact": "You don't have to carry around dongles for the 793 types of USB. Goats truly are universal."},
    {"fact": "There's no need to orchestrate goat deployments in the cloud."},
    {"fact": "Nobody will ever say <i>'Cattle, not pets!'</i> to you again."},
    {"fact": "Nobody will argue with you about whether you should be using Kanban or Scrum to milk your goats."},
    {"fact": "Nobody really gives a shit what color your goat shed is."},
    {"fact": "Your barn will never melt down because of the latest Intel® CPU bug."},
    {"fact": "When your goat speculates, it's just about what the next fucked up thing it's going to eat."},
    {"fact": "Your goats won't ever get 30% slower overnight after getting their shots."},
    {"fact": "Instead of 'blameless retrospectives', you just have goat steak for dinner."},
    {"fact": "Goats maintain their own Continuous Delivery pipeline."},
    {"fact": "Configuration management involves a rope or fencing"},
    {"fact": "The only Chef involved is in the kitchen."},
    {"fact": "The 'bit bucket' is the container your goat last tried to eat."},
    {"fact": "When a goat faints, it's adorable af."},
    {"fact": "You can't hook your servers up to a chariot and ride into town wielding a spear."},
    {"fact": "You'll never, ever, ever have to rebase a goat."},
    {"fact": "You will never receive LinkedIn network invites from a goat."},
    {"fact": "You do not need an excruciatingly long followup meeting with your goats."},
    {"fact": "Goats don't call you every Monday morning because they forgot their password over the weekend."},
    {"fact": "Goats cannot be phished."},
    {"fact": "Goats will eat stray flashdrives, rather than plug them in."},
    {"fact": "China, Russia, and North Korea will not attempt to infiltrate your goat farm."},
    {"fact": "Goats don’t drop packets; they drop deuces."},
    {"fact": "Goats, unlike stacks, cannot overflow."},
    {"fact": "No one has ever tried to encrypt a goat, nor do they complain when your goats are not encrypted."},
    {"fact": "Goats do not require a data classification, and they just eat data privacy statements."},
    {"fact": "Goats measure progress in food eaten, not lines of code."},
    {"fact": "Goat containers do not require kubernetes or Docker. They require wire fencing."},
    {"fact": "No goat has ever refused to produce output because they are out of toner or the fuser is toast. Output will never be a problem with goats."},
    {"fact": "Goats do not remove your ability to have goats on-premise and insist you can only have goats in the cloud from now on."},
    {"fact": "Goats will never penalize you for wanting to run your own goats on-premise (although your neighbors may)."},
    {"fact": "Goats will not pretend to like you just because you run the farm. If a goat does not like you, you <i>will</i> be aware of it."},
    {"fact": "Replacing your senior, high-producing goat with two junior goats that produce a quarter of the output is appropriately regarded as asinine."},
    {"fact": "If your goats have a problem working with the new goat from that other goat vendor, they will sort that out on their own. The most you'll have to do is referee."},
    {"fact": "Goats do not remove your ability to milk them because 'we find most people aren't taking advantage of goat milking as a feature'."},
    {"fact": "Goats will not rick-roll you"},
    {"fact": "Goats prefer neither tabs nor spaces. They are goats."},
    {"fact": "Goats are not affected by global pandemics."},
    {"fact": "Goats don't deploy straight to production, bypassing the dev and QA environments entirely."},
    {"fact": "Goats don't ignore valid and excellent suggestions for management improvement."},
    {"fact": "Goats don't hire your agency to add bandages to their poorly-constructed website, only to blame you later for its poor construction."},
    {"fact": "Goats are not concerned with deadlines."},
    {"fact": "Goats do not need to be fed yesterday, or the week before that.  They just want to be fed."},
    {"fact": "Goats do not require you to have a CS degree regardless of your level of expertise."},
    {"fact": "Goats don't flame your agency on social."},
    {"fact": "Goats do not require the farm staff to downsize 50%, then require the staff to continue to perform the same tasks with the same efficiency."},
    {"fact": "Goats don't have a particular preference between Java and C#."},
    {"fact": "Goats will never expect you to comply with separation of duties"},
    {"fact": "Goat is goat and there will never be something like microgoat."}
  ]);